name: github-pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Build documentation
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14 doxygen/1.13.2 pandoc/3.6.4
          python setup.py build_ext --inplace
          cd doc
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/doc/build/html
