name: qa

on:
  pull_request:
    branches:
      - main

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: clang-format style check
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '14'
          check-path: .
          exclude-regex: '(.\/doc\/|.\/resources\/|.\/tutorials\/|.\/external\/)'

  check-lua:
    name: Check Lua formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --check -f ${{ github.workspace }}/.stylua.toml ${{ github.workspace }}

  check-spdx-tags:
    name: check spdx tags
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kt3k/license_checker@v1.0.6

  check-flake8:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
