name: Weekly Tests

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: build
        shell: bash
        run: |
          export MODULEPATH=/scratch-local/software/modulefiles
          module load opensn/gcc/12.3.0
          mkdir build && cd build && cmake .. && make -j && cd ..
      - name: test
        shell: bash
        run: |
          export MODULEPATH=/scratch-local/software/modulefiles
          module load opensn/gcc/12.3.0
          test/run_tests -d test/ -j 32 -v 1 -w 4
